# Generated by Django 5.0.6 on 2024-06-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_bin_no', models.IntegerField()),
                ('card_type', models.CharField(max_length=40)),
                ('expiry_date', models.DateField()),
                ('cvv', models.IntegerField()),
                ('card_holder_name', models.CharField(max_length=40)),
                ('issuing_bank', models.CharField(max_length=255)),
                ('breach_date', models.DateField()),
                ('breach_source', models.CharField(max_length=255)),
                ('last_used_date', models.DateField()),
                ('severity_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
            ],
        ),
    ]
