# Generated by Django 5.0.6 on 2024-06-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dark_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_bin_no',
        ),
        migrations.AddField(
            model_name='card',
            name='card_bin_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Card BIN Number'),
        ),
        migrations.AlterField(
            model_name='card',
            name='breach_date',
            field=models.DateField(blank=True, null=True, verbose_name='Breach Date'),
        ),
        migrations.AlterField(
            model_name='card',
            name='breach_source',
            field=models.CharField(max_length=255, verbose_name='Breach Source'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Card Holder Name'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Card Type'),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.IntegerField(blank=True, null=True, verbose_name='CVV'),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='card',
            name='issuing_bank',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Issuing Bank'),
        ),
        migrations.AlterField(
            model_name='card',
            name='last_used_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Used Date'),
        ),
        migrations.AlterField(
            model_name='card',
            name='severity_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10, verbose_name='Severity Level'),
        ),
    ]
