# Generated by Django 5.0.6 on 2024-06-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dark_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='breach_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
