# Generated by Django 5.0.6 on 2024-06-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dark_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackMarket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255)),
                ('stealer_log_preview', models.TextField()),
                ('related_assets', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('unavailable', 'Unavailable')], max_length=12)),
                ('obtain_progress', models.CharField(max_length=255)),
                ('discovery_date', models.DateField()),
                ('incident', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain_ip', models.GenericIPAddressField()),
                ('severity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=6)),
                ('source_ip', models.GenericIPAddressField()),
                ('source_domain', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PIIExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('breach_date', models.DateField()),
                ('breach_ip', models.GenericIPAddressField()),
                ('domain', models.CharField(max_length=255)),
                ('threat_type', models.CharField(max_length=255)),
                ('severity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=6)),
                ('type_of_data', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('personal_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StealerLogs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_detected', models.DateField()),
                ('data_type', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('details', models.TextField()),
            ],
        ),
    ]
