# Generated by Django 5.0.6 on 2024-06-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dark_web', '0002_domain_breach_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='severity_level',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='severity_level',
        ),
        migrations.RemoveField(
            model_name='piiexposure',
            name='severity_level',
        ),
    ]
