# Generated by Django 5.0.6 on 2024-06-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dark_web', '0002_remove_card_card_bin_no_card_card_bin_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='breach_source_domain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Breach Source Domain'),
        ),
    ]
