# Generated by Django 5.0.6 on 2024-06-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dark_web', '0002_blackmarket_domain_piiexposure_stealerlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackmarket',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Unavailable', 'Unavailable')], max_length=12),
        ),
        migrations.AlterField(
            model_name='domain',
            name='severity_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=6),
        ),
        migrations.AlterField(
            model_name='piiexposure',
            name='severity_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=6),
        ),
    ]
