# Generated by Django 5.0.6 on 2024-06-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dark_web', '0003_notification_remove_card_severity_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_title', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
