# Generated by Django 5.0.6 on 2024-06-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dark_web', '0003_alter_blackmarket_status_alter_domain_severity_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piiexposure',
            name='breach_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='piiexposure',
            name='breach_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='piiexposure',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='piiexposure',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='piiexposure',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='piiexposure',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='piiexposure',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='piiexposure',
            name='threat_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='piiexposure',
            name='type_of_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
