# Generated by Django 5.0.6 on 2024-06-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='about',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='vision',
        ),
        migrations.AddField(
            model_name='organization',
            name='total_users',
            field=models.IntegerField(default=0),
        ),
    ]
